# lineareg/sim/__init__.py
"""Simulation and Monte Carlo testing module."""
from .montecarlo import (
    simulate_cs_data,
    simulate_ddd_data,
    simulate_dr_data,
    simulate_gls_data,
    simulate_iv_data,
    simulate_ols_data,
    simulate_qr_data,
    simulate_sar_data,
    simulate_sc_data,
    simulate_sdid_data,
    simulate_spatial_did_data,
    test_cs,
    test_ddd,
    test_dr,
    test_gls,
    test_gmm,
    test_iv,
    test_ivqr,
    test_ols,
    test_qr,
    test_sar,
    test_sc,
    test_sdid,
    test_spatial_did,
)

__all__ = [
    # Data generators
    "simulate_cs_data",
    "simulate_ddd_data",
    "simulate_dr_data",
    "simulate_gls_data",
    "simulate_iv_data",
    "simulate_ols_data",
    "simulate_qr_data",
    "simulate_sar_data",
    "simulate_sc_data",
    "simulate_sdid_data",
    "simulate_spatial_did_data",
    # Test functions
    "test_cs",
    "test_ddd",
    "test_dr",
    "test_gls",
    "test_gmm",
    "test_iv",
    "test_ivqr",
    "test_ols",
    "test_qr",
    "test_sar",
    "test_sc",
    "test_sdid",
    "test_spatial_did",
]
